<?php

namespace App\Enums;

use App\Traits\EnumHelpers;
use App\Traits\HasLabel;

enum Countries: string
{
    use EnumHelpers , HasLabel;

    case ALBANIA = 'Albania';
    case ANGOLA = 'Angola';
    case ARGENTINA = 'Argentina';
    case AUSTRIA = 'Austria';
    case AUSTRALIA = 'Australia';
    case BOSNIA = 'Bosnia';
    case BELGIUM = 'Belgium';
    case BURKINA_FASO = 'Burkina Faso';
    case BULGARIA = 'Bulgaria';
    case BURUNDI = 'Burundi';
    case BOLIVIA = 'Bolivia';
    case BRAZIL = 'Brazil';
    case BOTSWANA = 'Botswana';
    case BELARUS = 'Belarus';
    case CANADA = 'Canada';
    case CONGO_KINSHASA = 'Congo (Kinshasa)';
    case SWITZERLAND = 'Switzerland';
    case CHILE = 'Chile';
    case CHINA = 'China';
    case COLOMBIA = 'Colombia';
    case COSTA_RICA = 'Costa Rica';
    case CUBA = 'Cuba';
    case CYPRUS = 'Cyprus';
    case CZECH_REPUBLIC = 'Czech Republic';
    case GERMANY = 'Germany';
    case DENMARK = 'Denmark';
    case DOMINICAN_REPUBLIC = 'Dominican Republic';
    case ALGERIA = 'Algeria';
    case ECUADOR = 'Ecuador';
    case SPAIN = 'Spain';
    case ESTONIA = 'Estonia';
    case ETHIOPIA = 'Ethiopia';
    case FINLAND = 'Finland';
    case FRANCE = 'France';
    case UNITED_KINGDOM = 'United Kingdom';
    case GABON = 'Gabon';
    case GEORGIA = 'Georgia';
    case GHANA = 'Ghana';
    case GREECE = 'Greece';
    case GUATEMALA = 'Guatemala';
    case HUNGARY = 'Hungary';
    case INDONESIA = 'Indonesia';
    case INDIA = 'India';
    case IRELAND = 'Ireland';
    case IRAN = 'Iran';
    case ICELAND = 'Iceland';
    case ISRAEL = 'Israel';
    case ITALY = 'Italy';
    case IVORY_COAST = 'Ivory Coast';
    case JAPAN = 'Japan';
    case KAZAKHSTAN = 'Kazakhstan';
    case KENYA = 'Kenya';
    case KUWAIT = 'Kuwait';
    case LATVIA = 'Latvia';
    case LEBANON = 'Lebanon';
    case LIBYA = 'Libya';
    case LITHUANIA = 'Lithuania';
    case LUXEMBOURG = 'Luxembourg';
    case MADAGASCAR = 'Madagascar';
    case MALAYSIA = 'Malaysia';
    case MALI = 'Mali';
    case MEXICO = 'Mexico';
    case MOLDOVA = 'Moldova';
    case MONACO = 'Monaco';
    case MONTENEGRO = 'Montenegro';
    case MOROCCO = 'Morocco';
    case MOZAMBIQUE = 'Mozambique';
    case NAMIBIA = 'Namibia';
    case NETHERLANDS = 'Netherlands';
    case NEW_ZEALAND = 'New Zealand';
    case NICARAGUA = 'Nicaragua';
    case NIGER = 'Niger';
    case NIGERIA = 'Nigeria';
    case NORTH_MACEDONIA = 'North Macedonia';
    case NORWAY = 'Norway';
    case OMAN = 'Oman';
    case PAKISTAN = 'Pakistan';
    case PANAMA = 'Panama';
    case PARAGUAY = 'Paraguay';
    case PERU = 'Peru';
    case PHILIPPINES = 'Philippines';
    case POLAND = 'Poland';
    case PORTUGAL = 'Portugal';
    case QATAR = 'Qatar';
    case ROMANIA = 'Romania';
    case RUSSIA = 'Russia';
    case RWANDA = 'Rwanda';
    case SAUDI_ARABIA = 'Saudi Arabia';
    case SENEGAL = 'Senegal';
    case SERBIA = 'Serbia';
    case SINGAPORE = 'Singapore';
    case SLOVAKIA = 'Slovakia';
    case SLOVENIA = 'Slovenia';
    case SOMALIA = 'Somalia';
    case SOUTH_AFRICA = 'South Africa';
    case SOUTH_KOREA = 'South Korea';
    case SUDAN = 'Sudan';
    case SWEDEN = 'Sweden';
    case SYRIA = 'Syria';
    case TAJIKISTAN = 'Tajikistan';
    case TANZANIA = 'Tanzania';
    case THAILAND = 'Thailand';
    case TUNISIA = 'Tunisia';
    case TURKEY = 'Turkey';
    case UKRAINE = 'Ukraine';
    case UNITED_ARAB_EMIRATES = 'United Arab Emirates';
    case UNITED_STATES = 'United States';
    case UZBEKISTAN = 'Uzbekistan';
    case VENEZUELA = 'Venezuela';
    case VIETNAM = 'Vietnam';
    case YEMEN = 'Yemen';
    case ZAMBIA = 'Zambia';
    case ZIMBABWE = 'Zimbabwe';

    public function label(): string
    {
        return match ($this) {
            self::ALBANIA => 'آلبانی',
            self::ANGOLA => 'آنگولا',
            self::ARGENTINA => 'آرژانتین',
            self::AUSTRIA => 'اتریش',
            self::AUSTRALIA => 'استرالیا',
            self::BOSNIA => 'بوسنی',
            self::BELGIUM => 'بلژیک',
            self::BURKINA_FASO => 'بورکینافاسو',
            self::BULGARIA => 'بلغارستان',
            self::BURUNDI => 'بوروندی',
            self::BOLIVIA => 'بولیوی',
            self::BRAZIL => 'برزیل',
            self::BOTSWANA => 'بوتسوانا',
            self::BELARUS => 'بلاروس',
            self::CANADA => 'کانادا',
            self::CONGO_KINSHASA => 'کنگو (کینشازا)',
            self::SWITZERLAND => 'سوئیس',
            self::CHILE => 'شیلی',
            self::CHINA => 'چین',
            self::COLOMBIA => 'کلمبیا',
            self::COSTA_RICA => 'کاستاریکا',
            self::CUBA => 'کوبا',
            self::CYPRUS => 'قبرس',
            self::CZECH_REPUBLIC => 'جمهوری چک',
            self::GERMANY => 'آلمان',
            self::DENMARK => 'دانمارک',
            self::DOMINICAN_REPUBLIC => 'جمهوری دومینیکن',
            self::ALGERIA => 'الجزایر',
            self::ECUADOR => 'اکوادور',
            self::SPAIN => 'اسپانیا',
            self::ESTONIA => 'استونی',
            self::ETHIOPIA => 'اتیوپی',
            self::FINLAND => 'فنلاند',
            self::FRANCE => 'فرانسه',
            self::UNITED_KINGDOM => 'بریتانیا',
            self::GABON => 'گابن',
            self::GEORGIA => 'گرجستان',
            self::GHANA => 'غنا',
            self::GREECE => 'یونان',
            self::GUATEMALA => 'گواتمالا',
            self::HUNGARY => 'مجارستان',
            self::INDONESIA => 'اندونزی',
            self::INDIA => 'هند',
            self::IRELAND => 'ایرلند',
            self::IRAN => 'ایران',
            self::ICELAND => 'ایسلند',
            self::ISRAEL => 'اسرائیل',
            self::ITALY => 'ایتالیا',
            self::IVORY_COAST => 'ساحل عاج',
            self::JAPAN => 'ژاپن',
            self::KAZAKHSTAN => 'قزاقستان',
            self::KENYA => 'کنیا',
            self::KUWAIT => 'کویت',
            self::LATVIA => 'لتونی',
            self::LEBANON => 'لبنان',
            self::LIBYA => 'لیبی',
            self::LITHUANIA => 'لیتوانی',
            self::LUXEMBOURG => 'لوکزامبورگ',
            self::MADAGASCAR => 'ماداگاسکار',
            self::MALAYSIA => 'مالزی',
            self::MALI => 'مالی',
            self::MEXICO => 'مکزیک',
            self::MOLDOVA => 'مولداوی',
            self::MONACO => 'موناکو',
            self::MONTENEGRO => 'مونته‌نگرو',
            self::MOROCCO => 'مراکش',
            self::MOZAMBIQUE => 'موزامبیک',
            self::NAMIBIA => 'نامیبیا',
            self::NETHERLANDS => 'هلند',
            self::NEW_ZEALAND => 'نیوزلند',
            self::NICARAGUA => 'نیکاراگوئه',
            self::NIGER => 'نیجر',
            self::NIGERIA => 'نیجریه',
            self::NORTH_MACEDONIA => 'مقدونیه شمالی',
            self::NORWAY => 'نروژ',
            self::OMAN => 'عمان',
            self::PAKISTAN => 'پاکستان',
            self::PANAMA => 'پاناما',
            self::PARAGUAY => 'پاراگوئه',
            self::PERU => 'پرو',
            self::PHILIPPINES => 'فیلیپین',
            self::POLAND => 'لهستان',
            self::PORTUGAL => 'پرتغال',
            self::QATAR => 'قطر',
            self::ROMANIA => 'رومانی',
            self::RUSSIA => 'روسیه',
            self::RWANDA => 'رواندا',
            self::SAUDI_ARABIA => 'عربستان سعودی',
            self::SENEGAL => 'سنگال',
            self::SERBIA => 'صربستان',
            self::SINGAPORE => 'سنگاپور',
            self::SLOVAKIA => 'اسلواکی',
            self::SLOVENIA => 'اسلوونی',
            self::SOMALIA => 'سومالی',
            self::SOUTH_AFRICA => 'آفریقای جنوبی',
            self::SOUTH_KOREA => 'کره جنوبی',
            self::SUDAN => 'سودان',
            self::SWEDEN => 'سوئد',
            self::SYRIA => 'سوریه',
            self::TAJIKISTAN => 'تاجیکستان',
            self::TANZANIA => 'تانزانیا',
            self::THAILAND => 'تایلند',
            self::TUNISIA => 'تونس',
            self::TURKEY => 'ترکیه',
            self::UKRAINE => 'اوکراین',
            self::UNITED_ARAB_EMIRATES => 'امارات',
            self::UNITED_STATES => 'ایالات متحده',
            self::UZBEKISTAN => 'ازبکستان',
            self::VENEZUELA => 'ونزوئلا',
            self::VIETNAM => 'ویتنام',
            self::YEMEN => 'یمن',
            self::ZAMBIA => 'زامبیا',
            self::ZIMBABWE => 'زیمبابوه',
        };
    }
}
